### ISSUE TITLE
is ng2-bs3-modal now supports angular 4 ?

### ISSUE THREAD

**Issue by Christian-Yang** [dougludlow/ng2-bs3-modal#169] opened 2017-04-11 02:31 UTC
if  support  ,how to update ?

thanks very much !

**Comment by dougludlow** [comment] 2017-04-19 19:10
Closing as a duplicate of https://github.com/dougludlow/ng2-bs3-modal/issues/160.

**Closed by dougludlow** 2017-04-19 19:10 UTC
Labels: duplicate
