### ISSUE TITLE
Model not fade in

### ISSUE THREAD

**Issue by AnsarSamad** [dougludlow/ng2-bs3-modal#175] opened 2017-04-23 07:01 UTC
![image](https://cloud.githubusercontent.com/assets/21130011/25311535/0b1b5746-2821-11e7-869d-d258e291d644.png)

@angular/cli: 1.0.0
@angular/core: 4.0.2
npm ng2-bs3-model -version  : 3.10.10

**Comment by arun-awnics** [comment] 2017-05-17 03:06
@AnsarSamad Can you share your code snippet where you are facing this issue or create a plunk?

**Comment by vernjensen** [comment] 2017-07-29 01:42
I'm actually having a similar issue where the modal is *sometimes* not fading out when I hit OK. It hits different degrees of faded out (i.e. the 'gray' background blocker placeholder gets to different states of translucency) but it never finishes.

It would be hard to share code, since this is part of a large project, but I am calling:

this.modal.close();

One other relevant piece of information is that I have this in my HTML of the current page:

<iframe [hidden]="!globals.reportDef.report.pdfBytesBase64 || globals.reportDef.report.pdfBytesBase64.length == 0" 
		id="pdfViewerIFrame" [ngStyle]="iFrameStyle" src="./Scripts/pdfViewer/viewer.html" (window:resize)="onResize($event)">
</iframe>

<div [hidden]="globals.reportDef.report.pdfBytesBase64 && globals.reportDef.report.pdfBytesBase64.length > 0">
  (stuff)
</div>

and the globals.reportDef.pdfBytesBase64 gets changed to trigger between the PDF being shown vs. not shown when I close the dialog. I'm not sure if this is relevant... if this somehow causes the dialog's closing to halt.

**Comment by vernjensen** [comment] 2017-07-29 01:45
![image](https://user-images.githubusercontent.com/11324073/28741136-e16e2334-73c4-11e7-8f05-0551ac888c96.png)

Here is a snippet of a screenshot showing the state after I dismissed the dialog, but the background blocker placeholder is still there. I cannot click or do anything to dismiss it.

**Comment by vernjensen** [comment] 2017-07-29 02:08
And my package.json is set to ng2-bs3-modal "=0.10.4"

I will try the latest version and see if it works better.

**Comment by vernjensen** [comment] 2017-07-29 02:10
I take that back. NPM shows that 0.10.4 is the latest version available. I'm confused? The original poster showed "3.10.10" as his ng2-bs3-modal version.... is he incorrect or am I?

**Comment by vernjensen** [comment] 2017-07-29 02:28
Additional info: I tried using the promise returned by modal.close(), adding a JavaScript console.log() call so I can see if it gets called. And even when the 'background blocker never fades out' issue occurs, the promise DOES STILL GET CALLED.

**Comment by vernjensen** [comment] 2017-07-29 02:39
Even more info:

I tried restructuring my code so that

 this.modal.close().then( (result) =>
{   
    Do stuff here
}

Is the structure, and that seems to 'fix' the issue. 

The problem is, "Do stuff here" involves sending a message to the server, and if the server returns an error, I actually want to display that in the dialog, so having it already closed by this point is a problem.

"Do stuff here" also changes the globals.reportDef.report.pdfBytesBase64 that I mentioned earlier triggers an Angular2 change of the DOM, which might be somehow interfering with the dialog closing if this happens at the same time as the dialog closes. Waiting for the dialog to close first seems to avoid the issue.

I think the solution for me will be to use the original structure, but change it to dismiss instantly instead of fading.

**Comment by dougludlow** [comment] 2017-09-27 20:56
@vernjensen I've reworked the logic for this in v0.11. Hopefully less issues now.

**Closed by dougludlow** 2017-09-27 20:56 UTC
