### ISSUE TITLE
Two modal windows, the first does not scroll

### ISSUE THREAD

**Issue by vicabelotelova** [dougludlow/ng2-bs3-modal#201] opened 2017-09-21 05:40 UTC
I use two modal windows. When one is open, I must open the second window. But when I finish working in the second modal window, I should close it. And as a result, the first window does not scroll

**Comment by dougludlow** [comment] 2017-09-27 20:26
@vicabelotelova is this solved in the most recent version (v0.11.5)?

**Comment by vicabelotelova** [comment] 2017-09-28 06:46
@dougludlow it's not working in version 0.11.7. After closing the second modal window, the first window modal not scrolling. Thank you for you perfect feedback. If you can fix it soon as you can please

**Comment by dougludlow** [comment] 2017-10-02 15:08
@vicabelotelova I was finally able to repro this and have got a fix in the works. I'll let you know when I've got it published.

**Comment by dougludlow** [comment] 2017-10-02 20:58
Duplicate of #57.

**Closed by dougludlow** 2017-10-02 20:58 UTC
Labels: bug
